- name: Install a package on Windows
  hosts: windows
  vars:
    installer: xagtSetup_35.31.22_universal.msi
    config_file: agent_config.json
    repo_url: 'http://astolfo.poorware.tk/binaries/'

  tasks:

    - name: Create a files directory for saving assets
      ansible.builtin.file:
        path: files
        mode: '0755'
        state: directory
         
    - name: Get installer and support files from repository if not present in the source tree
      ansible.builtin.get_url:
        url: "{{ repo_url }}/{{ item }}"
        dest: files/{{ item }}
        mode: '644'
      # when: not lookup('fileglob', 'files/' + item)
      loop:
        - "{{ installer }}"
        - "{{ config_file }}"
      delegate_to: localhost
      run_once: true

    - name: Copy installation files over to the managed node
      ansible.windows.win_copy:
        src: files/{{ item }}
        dest: 'c:\'
      loop:
        - "{{ installer }}"
        - "{{ config_file }}"

    - name: Install package quietly using Windows Installer
      ansible.windows.win_package:
        path: 'c:\{{ installer }}'
        product_id: "{80D6156C-6E16-445B-B077-0C9E050CC1B0}"
        chdir: 'c:\'
        provider: msi
        state: present
